### ISSUE TITLE
Minimum OpenCV version

### ISSUE THREAD

**Issue by robinloujun** [hyye/lio-mapping#1]
Hi there, 

thanks a lot for the nice work.

I think there should be a minimum vision (3.4.2, seeing this [question](https://answers.opencv.org/question/198488/undefined-reference-to-cvmatupdatecontinuityflag/)) set for OpenCV, otherwise it meets error like
```shell
estimator_node.cc:(.text+0x9a1): undefined reference to `cv::Mat::updateContinuityFlag()'
```

**Comment by hyye** [comment]
Hi @robinloujun, thanks for your report. I think this might be related to some specific versions of OpenCV, like 3.3.1. In my PC or docker, it works with version 3.2.0.

**Comment by robinloujun** [comment]
You are right, the default opencast version of rod-kinetic is 3.3.1
